hook.Add( "AddToolMenuCategories", "GoldSrcBulletOptionsCategory", function()
	spawnmenu.AddToolCategory( "Options", "GoldSrc", "#GoldSrc" )
end )

hook.Add( "PopulateToolMenu", "GoldSrcBulletOptionsMenu", function()
	spawnmenu.AddToolMenuOption( "Options", "GoldSrc", "GoldSrcBulletOptions", "#GoldSrc Bullets", "", "", function( panel )
		panel:ClearControls()
        panel:CheckBox("Enable particles", "gsrc_bullets_particles")
        panel:CheckBox("Enable ricochet sound", "gsrc_bullets_ricochet")
        local combobox = panel:ComboBox( "Mode", "gsrc_bullets_mode")

        combobox:AddChoice("Half-Life 1", "hl1")
        combobox:AddChoice("Counter-Strike 1.6", "cs16")
	end )
end )
